query {
  weapons {
    damage_type
    description
    icon
    name
    perks
    stat_aim_assistance
    stat_ammo_capacity
    stat_blast_radius
    stat_charge_time
    stat_defense
    stat_efficiency
    stat_handling
    stat_impact
    stat_magazine
    stat_range
    stat_recoil_direction
    stat_reload_speed
    stat_rounds_per_minute
    stat_stability
    stat_swing_speed
    stat_velocity
    stat_zoom
    tier
    type
    zoom_levels
  }
}
